"use client"

import { useState, useRef } from "react"
import { Copy, Check, Download, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { WCA_EVENTS, getEventLabel } from "@/lib/constants"
import type { WcaEventId } from "@/lib/constants"
import { generateScramble } from "@/lib/timer/scrambles"
import { cn } from "@/lib/utils"

const MAX_SCRAMBLES = 999
const SCRAMBLE_EVENTS = WCA_EVENTS.filter(
  (e) => e.id !== "333fm" && e.id !== "333mbf"
)

export function BatchScrambleGenerator() {
  const [event, setEvent] = useState<WcaEventId>("333")
  const [count, setCount] = useState(12)
  const [scrambles, setScrambles] = useState<string[]>([])
  const [isGenerating, setIsGenerating] = useState(false)
  const [copied, setCopied] = useState(false)
  const listRef = useRef<HTMLDivElement>(null)

  const handleGenerate = () => {
    setIsGenerating(true)
    setScrambles([])

    // Generate in batches to avoid blocking UI
    const results: string[] = []
    const batchSize = 50
    let generated = 0

    const generateBatch = () => {
      const end = Math.min(generated + batchSize, count)
      for (let i = generated; i < end; i++) {
        results.push(generateScramble(event))
      }
      generated = end

      if (generated < count) {
        setScrambles([...results])
        requestAnimationFrame(generateBatch)
      } else {
        setScrambles(results)
        setIsGenerating(false)
      }
    }

    requestAnimationFrame(generateBatch)
  }

  const handleCopyAll = async () => {
    if (scrambles.length === 0) return
    const text = scrambles
      .map((s, i) => `${i + 1}. ${s}`)
      .join("\n")
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Clipboard API not available
    }
  }

  const handleCopySingle = async (scramble: string) => {
    try {
      await navigator.clipboard.writeText(scramble)
    } catch {
      // Clipboard API not available
    }
  }

  const handleDownload = () => {
    if (scrambles.length === 0) return
    const eventLabel = getEventLabel(event)
    const text = [
      `${eventLabel} Scrambles (${scrambles.length})`,
      `Generated by SpeedCubeHub`,
      "",
      ...scrambles.map((s, i) => `${i + 1}. ${s}`),
    ].join("\n")

    const blob = new Blob([text], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${eventLabel.toLowerCase().replace(/\s+/g, "-")}_scrambles_${scrambles.length}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleCountChange = (value: string) => {
    const num = parseInt(value)
    if (isNaN(num)) {
      setCount(0)
      return
    }
    setCount(Math.min(Math.max(1, num), MAX_SCRAMBLES))
  }

  return (
    <div className="max-w-3xl mx-auto px-4 py-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Batch Scramble Generator</h1>
        <p className="text-muted-foreground text-sm mt-1">
          Generate up to {MAX_SCRAMBLES} scrambles for any WCA event
        </p>
      </div>

      {/* Controls */}
      <div className="flex flex-wrap items-end gap-3">
        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-muted-foreground">
            Event
          </label>
          <select
            value={event}
            onChange={(e) => setEvent(e.target.value as WcaEventId)}
            className="h-10 px-3 rounded-md border border-border bg-secondary/50 text-sm min-w-[140px]"
          >
            {SCRAMBLE_EVENTS.map((e) => (
              <option key={e.id} value={e.id}>
                {e.label}
              </option>
            ))}
          </select>
        </div>

        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-muted-foreground">
            Count
          </label>
          <input
            type="number"
            min={1}
            max={MAX_SCRAMBLES}
            value={count || ""}
            onChange={(e) => handleCountChange(e.target.value)}
            className="h-10 w-24 px-3 rounded-md border border-border bg-secondary/50 text-sm font-mono text-center"
          />
        </div>

        <Button
          onClick={handleGenerate}
          disabled={isGenerating || count < 1}
          className="h-10"
        >
          {isGenerating ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin mr-1.5" />
              Generating...
            </>
          ) : (
            "Generate"
          )}
        </Button>
      </div>

      {/* Quick count buttons */}
      <div className="flex flex-wrap gap-2">
        {[5, 12, 25, 50, 100, 200, 500].map((n) => (
          <button
            key={n}
            onClick={() => setCount(n)}
            className={cn(
              "px-3 py-1 rounded-full text-xs font-medium border transition-colors",
              count === n
                ? "border-primary bg-primary/15 text-primary"
                : "border-border text-muted-foreground hover:border-foreground/30"
            )}
          >
            {n}
          </button>
        ))}
      </div>

      {/* Results */}
      {scrambles.length > 0 && (
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <p className="text-sm text-muted-foreground">
              {scrambles.length} {getEventLabel(event)} scramble{scrambles.length !== 1 ? "s" : ""}
              {isGenerating && ` (generating...)`}
            </p>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={handleCopyAll}
                className="h-8 gap-1.5"
              >
                {copied ? (
                  <Check className="h-3.5 w-3.5 text-green-400" />
                ) : (
                  <Copy className="h-3.5 w-3.5" />
                )}
                Copy All
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={handleDownload}
                className="h-8 gap-1.5"
              >
                <Download className="h-3.5 w-3.5" />
                Download
              </Button>
            </div>
          </div>

          <div
            ref={listRef}
            className="border border-border rounded-lg overflow-y-auto max-h-[60vh] divide-y divide-border/50"
          >
            {scrambles.map((scramble, i) => (
              <div
                key={i}
                className="flex items-center gap-3 px-3 py-2 hover:bg-secondary/30 transition-colors group"
              >
                <span className="text-xs text-muted-foreground font-mono w-8 text-right shrink-0">
                  {i + 1}.
                </span>
                <span className="font-mono text-sm flex-1 min-w-0 break-words">
                  {scramble}
                </span>
                <button
                  onClick={() => handleCopySingle(scramble)}
                  className="p-1 rounded opacity-0 group-hover:opacity-100 hover:bg-secondary transition-all text-muted-foreground hover:text-foreground shrink-0"
                  title="Copy scramble"
                >
                  <Copy className="h-3.5 w-3.5" />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
