import type { Solve } from "@/lib/types"
import { getEffectiveTime, formatTimeMs, computeSessionStats } from "@/lib/timer/averages"
import { getEventLabel } from "@/lib/constants"

// ── CSV Export ────────────────────────────────────────────────────────

export function solvesToCSV(solves: Solve[], event: string): string {
  const header = "No.,Time (ms),Penalty,Effective Time,Scramble,Date,Notes"
  const rows = solves.map((s, i) => {
    const effective = getEffectiveTime(s)
    const effectiveStr = effective === Infinity ? "DNF" : String(effective)
    const time = formatSolveForExport(s)
    const scramble = csvEscape(s.scramble ?? "")
    const date = new Date(s.solved_at).toISOString()
    const notes = csvEscape(s.notes ?? "")
    return `${i + 1},${s.time_ms},${s.penalty ?? ""},${effectiveStr},${scramble},${date},${notes}`
  })

  return [
    `# Event: ${getEventLabel(event)}`,
    `# Solves: ${solves.length}`,
    `# Exported: ${new Date().toISOString()}`,
    header,
    ...rows,
  ].join("\n")
}

function csvEscape(value: string): string {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}

// ── JSON Export ───────────────────────────────────────────────────────

export function solvesToJSON(solves: Solve[], event: string): string {
  const stats = computeSessionStats(solves)
  const data = {
    event: getEventLabel(event),
    eventId: event,
    exportedAt: new Date().toISOString(),
    stats: {
      count: stats.count,
      best: stats.best,
      mean: stats.mean,
      ao5: stats.ao5,
      ao12: stats.ao12,
      bestAo5: stats.bestAo5,
      bestAo12: stats.bestAo12,
    },
    solves: solves.map((s, i) => ({
      number: i + 1,
      timeMs: s.time_ms,
      penalty: s.penalty,
      effectiveMs: getEffectiveTime(s) === Infinity ? null : getEffectiveTime(s),
      scramble: s.scramble,
      date: s.solved_at,
      notes: s.notes,
    })),
  }
  return JSON.stringify(data, null, 2)
}

// ── csTimer TXT Export ───────────────────────────────────────────────

export function solvesToCsTimerTxt(solves: Solve[], event: string): string {
  const stats = computeSessionStats(solves)
  const lines: string[] = []

  lines.push(`Generated By: Speed Cube Hub`)
  lines.push(`Event: ${getEventLabel(event)}`)
  lines.push(`Solves: ${solves.length}`)
  lines.push(``)

  // Stats summary
  if (stats.best !== null) lines.push(`single: ${formatTimeMs(stats.best)}`)
  if (stats.mean !== null) lines.push(`mean: ${formatTimeMs(stats.mean)}`)
  if (stats.ao5 !== null) lines.push(`ao5: ${formatTimeMs(stats.ao5)}`)
  if (stats.ao12 !== null) lines.push(`ao12: ${formatTimeMs(stats.ao12)}`)
  if (stats.bestAo5 !== null) lines.push(`best ao5: ${formatTimeMs(stats.bestAo5)}`)
  if (stats.bestAo12 !== null) lines.push(`best ao12: ${formatTimeMs(stats.bestAo12)}`)
  lines.push(``)

  // Time list
  lines.push(`Time List:`)
  for (let i = 0; i < solves.length; i++) {
    const s = solves[i]
    const time = formatSolveForExport(s)
    const scramble = s.scramble ? `   ${s.scramble}` : ""
    lines.push(`${i + 1}. ${time}${scramble}`)
  }

  return lines.join("\n")
}

// ── Stats to Clipboard ───────────────────────────────────────────────

export function statsToClipboard(solves: Solve[], event: string): string {
  const stats = computeSessionStats(solves)
  const lines: string[] = []

  lines.push(`${getEventLabel(event)} — ${stats.count} solves`)
  if (stats.best !== null) lines.push(`Best: ${formatTimeMs(stats.best)}`)
  if (stats.mean !== null) lines.push(`Mean: ${formatTimeMs(stats.mean)}`)
  if (stats.ao5 !== null) lines.push(`Ao5: ${formatTimeMs(stats.ao5)}`)
  if (stats.ao12 !== null) lines.push(`Ao12: ${formatTimeMs(stats.ao12)}`)
  if (stats.bestAo5 !== null) lines.push(`Best Ao5: ${formatTimeMs(stats.bestAo5)}`)
  if (stats.bestAo12 !== null) lines.push(`Best Ao12: ${formatTimeMs(stats.bestAo12)}`)

  return lines.join("\n")
}

// ── Shared Helpers ───────────────────────────────────────────────────

function formatSolveForExport(solve: Solve): string {
  if (solve.penalty === "DNF") return "DNF"
  const effective = getEffectiveTime(solve)
  const timeStr = formatTimeMs(effective)
  return solve.penalty === "+2" ? `${timeStr}+` : timeStr
}

// ── Download Helper ──────────────────────────────────────────────────

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
